name: spam_classifier_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn


